name: ubuntu-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: install updates
      run: |
        sudo apt install g++-10
        sudo apt install libbfd-dev
        wget -O cmake.sh https://cmake.org/files/v3.20/cmake-3.20.1-linux-x86_64.sh
        sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
        export PATH=/usr/local/bin:$PATH
        cmake --version
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.170-bionic.list https://packages.lunarg.com/vulkan/1.2.170/lunarg-vulkan-1.2.170-bionic.list
        sudo apt update
        sudo apt install vulkan-sdk
        sudo apt-get install libglfw3-dev

    - name: run build
      run: |
        cmake . -DCMAKE_CXX_COMPILER=g++-10
        make
