 
name: windows-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: install updates
      run: |
        curl -LS -o vulkansdk.exe `https://sdk.lunarg.com/sdk/download/${{ env.inexor_vulkan_version }}/windows/VulkanSDK-${{ env.inexor_vulkan_version }}-Installer.exe?Human=true
        7z x vulkansdk.exe -o"${{ env.inexor_vulkan_sdk }}"
    
    - name: run build
      run: |
        cmake . -DCMAKE_CXX_COMPILER=g++-11 -DPF_COMMON_TESTS=ON
        cmake --build . --target pf_common_tests
